In [1]:
import numpy as np

In [3]:
# check the version
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

## Creating Arrays

In [6]:
# create an array of all zeros
np.zeros(5) # creates an array of 5 0's

array([0., 0., 0., 0., 0.])

In [7]:
np.ones(10) # creates an array of 10 1's

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.full(10,2.5) # creates an array of 10 2.5's

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

## Converting Lists to Arrays

In [9]:
my_list = [2,3,4]
array_from_list = np.array(my_list)
array_from_list

array([2, 3, 4])

In [11]:
# get the second item from the array
array_from_list[1] # remember python 0 indexes!

np.int64(3)

In [12]:
# reassign the second item of the array to a new value
array_from_list[1] = 10
array_from_list

array([ 2, 10,  4])

## Generating Ranges of Numbers

In [13]:
range_array = np.arange(10) # create an array from 0 to 9
range_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# you can also se the specified start number
short_range_array = np.arange(3,10) # creates an array from 3 (inclusive) to 10 (exclusive)
short_range_array

array([3, 4, 5, 6, 7, 8, 9])

In [17]:
# create an array evenly spaced numbers within a range
linspace_array = np.linspace(0,1,11) # creates 11 numbers from 0 to 1
linspace_array

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

## Multi-Dimensional Arrays

In [19]:
zeroes_matrix = np.zeros((5,2))
zeroes_matrix # an array with 5 rows and 2 columns filled with zeroes (shape is (5,2)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [20]:
ones_matrix = np.ones((5,2))
ones_matrix # (5,2) array filled with ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

## Array Index and Slicing

In [21]:
arr = np.array([[2,3,4],
                [4,5,6]])
first_row = arr[0]
first_col = arr[:, 0]

print(first_row)
print(first_col)

[2 3 4]
[2 4]


In [22]:
# get the 3rd number of the second row
arr[1,2]

np.int64(6)

## Randomly Generated Arrays

In [35]:
np.random.seed(2) # specifiy the seed for reproducibility
random_array = np.random.rand(5,2)
random_array

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [36]:
# random numbers from a normal distribution
np.random.seed(2)
normal_dist = np.random.randn(5,2)
normal_dist

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [37]:
# random integers within a range
np.random.seed(2)
rand_ints = np.random.randint(low= 0, high=100, size=(5,2))
rand_ints

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## Array Operations

### Element-Wise Operations

In [41]:
# create an array for demo
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [42]:
# add 1 to each member of the array
a = a + 1
a

array([1, 2, 3, 4, 5])

In [43]:
# multiply each element by 2
a = a * 2
a
# works the same for other mathematical operations like division etc

array([ 2,  4,  6,  8, 10])

### Element-Wise Operations with Two Arrays

In [45]:
arr1 = np.ones(4)
arr1

array([1., 1., 1., 1.])

In [46]:
arr2 = np.full(4,3) # creates an array of length 4 full of 3's
arr2

array([3, 3, 3, 3])

In [47]:
result1 = arr1 + arr2 # adds each element together element wise
result1

array([4., 4., 4., 4.])

In [48]:
result2 = arr1 / arr2 # divides each number
result2

array([0.33333333, 0.33333333, 0.33333333, 0.33333333])

### Comparison Operations

In [51]:
# perform element-wise comparison
arr = np.array([1,2,3,4])
greater_than_2 = arr > 2 # produces an array of booleans representing rather that element is greater than 2 or not
greater_than_2

array([False, False,  True,  True])

### Selecting Elements Based on Conditions

In [52]:
selection = arr[arr>2] # selects elements that are True
selection

array([3, 4])

## Summary Operations

In [53]:
# minimum value
arr.min()

np.int64(1)

In [54]:
# max val
arr.max()

np.int64(4)

In [56]:
# sum of all elements
arr.sum()

np.int64(10)

In [57]:
# mean of all elements
arr.mean()

np.float64(2.5)

In [58]:
# standard deviation of all elements
arr.std()

np.float64(1.118033988749895)